apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "http.labels" . | nindent 4 }}
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.appName }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Values.appName }}
          {{- if .Values.image.repository }}
            {{- if .Values.image.tag  }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            {{ end }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          envFrom:
          - secretRef:
              name: {{ .Values.appName }}
          volumeMounts:
            - name: {{ .Values.appName }}
              mountPath: /data/{{ .Values.appName }}
      volumes:
        - name: {{ .Values.appName }}
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}
        
