apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-worker
  labels:
    {{- include "http.labels" . | nindent 4 }}
    app: {{ .Values.appName }}-worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.appName }}-worker
    spec: 
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}   
      containers:
        - name: {{ .Values.appName }}-worker
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.image.workerCommand | nindent 12 }}
          envFrom:
          - secretRef:
              name: {{ .Values.appName }}

