apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
        - name: flower
          image: mher/flower:2.0.1
          command: ["celery", "--broker=redis://redis:6379", "flower", "--address=0.0.0.0", "--port=5555"]
          ports:
            - containerPort: 5555
          env:
            - name: FLOWER_PORT
              value: "5555"
---
apiVersion: v1
kind: Service
metadata:
  name: flower
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 5555
      targetPort: 5555
  selector:
    app: flower